eurofurence/reg-frontend

gatsby-config.js
gatsby-node.js
package-lock.json
package.json
src/components/footer.tsx
src/components/header.tsx
src/components/layout.tsx
src/localization.ts
src/pages/register.tsx
src/queries/site-metadata.ts
static/localizations/en.ftl

Implementing the registration form in this draft PR.

Registration Form

---

src/components/register/steps/contact.tsx
src/components/register/steps/optional.tsx
src/components/register/steps/personal.tsx
src/components/register/steps/ticket/day.tsx
src/components/register/steps/ticket/level.tsx
src/components/register/steps/ticket/type.tsx
src/state/actions/autosave.ts
src/state/actions/index.ts
src/state/actions/register.ts
src/state/epics/autosave.ts
src/state/epics/index.ts
src/state/models/autosave.ts
src/state/reducers/autosave.ts
src/state/reducers/index.ts
src/state/reducers/register.ts

Autosaving feature

---

src/components/footer.tsx
src/components/register/footer.tsx
src/state/selectors/autosave.ts
static/localizations/en.ftl

Add last saved notice in footer

---

src/state/epics/register.ts

Fixes #37 
The compiler even pointed it out! :sweat_smile:

Fix issue #37

---

src/components/funnels/funnels/register/steps/ticket.tsx
src/components/funnels/funnels/register/steps/ticket/day.tsx
src/components/layout.tsx
src/navigation/router.tsx
static/localizations/en.ftl

Fix register routing issues

---

package-lock.json
package.json
src/apis/attsrv.ts
src/components/footer.tsx
src/components/funnels/funnels/register/steps/summary.tsx
src/components/funnels/funnels/register/steps/thank-you.tsx
src/components/funnels/layout/common.tsx
src/components/funnels/layout/splash.tsx
src/components/layout.tsx
src/config.ts
src/navigation/router.tsx
src/navigation/routes.ts
src/state/actions/index.ts
src/state/actions/register.ts
src/state/autosave.ts
src/state/epics/register.ts
src/state/models/hotel-booking.ts
src/state/models/register.ts
src/state/reducers/hotel-booking.ts
src/state/reducers/register.ts
src/state/selectors/hotel-booking.ts
src/state/selectors/register.ts
static/localizations/en.ftl

Missing a lot of stuff but quite big changes so already merging it in.

Add registration submission - initial version

---

package-lock.json
package.json
src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/personal.tsx
src/components/funnels/funnels/register/steps/summary.tsx
src/hooks/funnels/form.ts
src/state/actions/forms.ts
src/state/forms.ts
src/state/models/register.ts
src/state/reducers/register.ts
static/localizations/en.ftl

Adds pronouns. Incorporates @ErikMelton 's work but updated to work with the new forms and validations. Fixes #39

Add pronouns

---

src/components/funnels/funnels/register/steps/contact.tsx
src/components/funnels/funnels/register/steps/personal.tsx
src/hooks/funnels/form.ts
static/localizations/en.ftl

Bring validations in line with backend

---

src/components/funnels/funnels/register/layout/form/full-width.tsx
src/components/funnels/funnels/register/steps/ticket/day.tsx
src/components/funnels/layout/common.tsx
static/localizations/en.ftl

Add back button show override for edge cases

---

src/components/funnels/funnels/register/steps/personal.tsx
src/components/funnels/funnels/register/steps/summary.tsx
src/localizations/en.ftl
src/state/forms.ts
src/state/models/register.ts

Remove name on badge

---

src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/contact.tsx
src/localizations/en.ftl
src/state/forms.ts
src/state/models/register.ts

Add telegram username

---

src/components/funnels/funnels/register/steps/personal.tsx
src/config.ts
src/localizations/en.ftl
src/state/forms.ts
src/state/models/register.ts
src/state/reducers/register.ts

Add date of birth

---

.eslintrc.yml
package-lock.json
package.json
src/components/funnels/funnels/register/steps/contact.tsx
src/components/funnels/funnels/register/steps/personal.tsx
src/hooks/funnels/form.tsx
src/localizations/en.ftl

Add validation errors

---

src/components/footer.tsx
src/config.ts
src/localizations/en.ftl

Add footer links

---

src/apis/attsrv.ts
src/apis/common.ts
src/apis/paysrv.ts
src/components/funnels/funnels/register/not-open-yet.tsx
src/localizations/en.ftl
src/pages/register.tsx
src/state/actions/auth.ts
src/state/actions/index.ts
src/state/epics/auth.ts
src/state/epics/index.ts
src/state/epics/register.ts

Add countdown check on load

---

src/@types/global.d.ts
src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/personal.tsx
src/components/funnels/funnels/register/steps/ticket/level.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/addon.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/control.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/options/option.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/options/select.tsx
src/config.ts
src/localizations/en.ftl
src/state/forms.ts
src/state/models/register.ts
src/state/reducers/register.ts
src/state/selectors/register.ts

Generalized addons

---

src/@types/global.d.ts
src/components/funnels/funnels/register/steps/ticket/level.tsx
src/config.ts
src/state/reducers/register.ts

Allow marking addons as unavailable for a particular ticket type

---

gatsby-config.js
package-lock.json
package.json
src/components/funnels/error-report.tsx
src/components/funnels/funnels/register/not-open-yet.tsx
src/components/funnels/funnels/register/steps/thank-you.tsx
src/components/funnels/funnels/register/steps/ticket/day.tsx
src/components/funnels/funnels/register/steps/ticket/type.tsx
src/components/funnels/layout/splash.tsx
src/util/readonly-types.ts

Use optimized images

---

src/apis/authsrv.ts
src/components/layout.tsx
src/hooks/funnels/form.tsx
src/localizations/en.ftl
src/pages/register.tsx
src/state/actions/auth.ts
src/state/actions/autosave.ts
src/state/autosave.ts
src/state/epics/auth.ts
src/state/epics/autosave.ts
src/state/models/auth.ts
src/state/models/autosave.ts
src/state/models/errors.ts
src/state/reducers/auth.ts
src/state/reducers/hotel-booking.ts
src/state/reducers/index.ts
src/state/reducers/register.ts
src/state/selectors/auth.ts
src/state/selectors/autosave.ts
src/state/selectors/hotel-booking.ts
src/state/selectors/register.ts
src/util/local-storage.ts

Load user info

---

src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/personal.tsx
src/localizations/en.ftl
src/state/forms.ts
src/state/reducers/register.ts
src/state/selectors/forms.ts

Prefer not to say pronouns

---

package-lock.json
package.json
src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/summary.tsx
src/localizations/en.ftl
src/state/actions/register.ts
src/state/epics/register.ts
src/state/forms.ts
src/state/selectors/forms.ts

Add checkbox for rules and conditions

---

src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/ticket/level/addons/addon.tsx

Don't reset addon selection on first render

---

src/components/layout.tsx
src/localizations/en.ftl

Add a retry button to the unverified error screen

---

package-lock.json
package.json
src/apis/attsrv.ts
src/apis/authsrv.ts
src/apis/paysrv.ts
src/components/funnels/error-report.tsx
src/components/funnels/invoice/invoice.tsx

Add error details

---

src/components/error-guard.tsx
src/components/error-report.tsx
src/components/layout.tsx
src/pages/register.tsx

Let error handling work for authsrv errors

---

src/components/footer.tsx

Open links in new tab

---

src/components/funnels/funnels/register/steps/summary.tsx
src/localizations/de-DE.ftl
src/localizations/en-US.ftl

@Jumpy-Squirrel can you please add a German translation for this?

Registration status text

---

src/localizations/de-DE.ftl
src/localizations/en-US.ftl

Dealer's Den does open (super-)early on Tuesday as well, not just Monday. 
Requested by Pattarchus via Telegram

Localisation: Extended the (super-)sponsor days to tuesday

---

src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/summary.tsx
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/state/models/register.ts
src/state/selectors/autosave.ts
src/state/selectors/register.ts

Add dynamic status

---

src/apis/attsrv.ts
src/state/models/register.ts

Retain unknown packages and flags

---

package-lock.json
package.json
src/apis/attsrv.ts
src/components/funnels/funnels/register/layout/form/with-invoice.tsx
src/components/funnels/funnels/register/steps/summary.tsx
src/components/funnels/invoice/invoice.tsx
src/components/funnels/layout/with-invoice.tsx
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/state/models/invoice.ts
src/state/models/register.ts

fiddling with stuff while I test

Issue 207 fixes

---

src/components/funnels/funnels/register/steps/summary.tsx
src/localizations/de-DE.ftl
src/localizations/en-US.ftl

Add badge number in summary display

---

src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/ticket/level.tsx
src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/state/models/autosave.ts
src/util/config-types.ts

- add early bird discount and at the door late fee
- show all packages in the invoice
- configure all the addons/packages (but don't show in the form)

feat(#213): early bird discount and full invoices

---

.github/workflows/docker-build-push.yml
Dockerfile
httpd-container.conf
src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/ticket/level.tsx
src/components/funnels/funnels/register/steps/ticket/level/card.tsx
src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/state/epics/register.ts
src/state/models/autosave.ts
src/state/models/register.ts
src/state/reducers/register.ts
src/state/selectors/forms.ts

- technical configuration (apache logging, ability to disable frontend with apache still running)
- package configuration (allow modifiers to depend on ticket type, etc.)
- fix: stage pass and modifiers correctly changed when switching between day and full ticket during initial registration

Issue 213 preparations

---

.github/workflows/docker-build-push.yml
src/hooks/funnels/form.tsx
src/state/reducers/register.ts

Fixes for the frontend UI

---

src/localizations/de-DE.ftl
src/localizations/en-US.ftl

fix(#222): dd early access days

---

src/localizations/de-DE.ftl
src/localizations/en-US.ftl

- part of #222
- art show also has early access on Thursday

fix(#222): more wording

---

src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/util/config-types.ts

- some links still went to EF27
- liability waiver is no more
- don't say approve can take a few weeks, it's days this time

fix(#222): fix links and success message

---

httpd-container.conf

- pull out the brakes (noticed the problem during initial reg)

fix(#222): increase request limits

---

src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl

- closes #232 for reg-frontend

feat(#232): add dealer-fullplus package

---

src/config.ts

early bird is done

---

src/config.ts

configure boat package prices (frontend part)
closes #236

configure boat prices

---

.eslintrc.yml
src/apis/attsrv.ts
src/components/funnels/funnels/register/steps/ticket/level.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/addon.tsx
src/components/funnels/funnels/register/steps/ticket/level/addons/options/select.tsx
src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl
src/state/models/register.ts
src/state/reducers/register.ts
src/state/selectors/register.ts
src/util/config-types.ts

- part of #250 
Since this makes pretty significant changes to the config object, I have ported over the 2 MMC config options.

support booking package multiple times

---

src/apis/attsrv.ts
src/config.ts
src/localizations/de-DE.ftl
src/localizations/en-US.ftl

- part of #250 
Received feedback on wording and fursuitbadge rules.

package configuration and name fixes

---

src/localizations/de-DE.ftl
src/localizations/en-US.ftl

contribution received from @Treyfane

feat(#254): contributed text changes

---

src/components/funnels/funnels/register/steps/ticket/level/addons/addon.tsx
src/config.ts
src/util/config-types.ts

bugfix: only reset some addon selections during sponsor level change

---

src/config.ts

- part of #254 
configuration for first RC

further configuration

---

src/apis/attsrv.ts
src/state/models/register.ts
src/state/reducers/register.ts
src/state/selectors/register.ts

also reset ticket level on type change

---

src/localizations/de-DE.ftl
src/localizations/en-US.ftl

update deadlines for early/late

---

src/config.ts

configuration change to disable early bird

feat(#267): disable early bird for new regs

---

src/localizations/en-US.ftl

feat(#284): improve wording for paid status

---

src/config.ts

- fixes #286 
(forgot to also increment config version number)

fix(#286): increment version
